# Generated by Django 3.2 on 2022-06-07 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('profile_img', models.ImageField(blank=True, upload_to='resume/profile', verbose_name='Profile')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bie', models.TextField(blank=True, verbose_name='Bie')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1, verbose_name='Marital status')),
                ('militaryـstatus', models.CharField(choices=[(0, 'Subject'), (1, 'To Serving'), (2, 'EndـService'), (3, 'Exempt')], max_length=1, verbose_name='Military status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
