# Generated by Django 3.2 on 2022-06-07 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='militaryـstatus',
            field=models.IntegerField(choices=[(0, 'Subject'), (1, 'To Serving'), (2, 'EndـService'), (3, 'Exempt')], max_length=1, verbose_name='Military status'),
        ),
    ]
