# Generated by Django 3.2 on 2022-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='militaryـstatus',
            field=models.IntegerField(choices=[(0, 'Subject'), (1, 'To Serving'), (2, 'EndـService'), (3, 'Exempt')], verbose_name='Military status'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(0, 'Excellent'), (1, 'Good'), (2, 'Medium'), (3, 'Weak')], verbose_name='Level'),
        ),
    ]
