# Generated by Django 3.2 on 2022-06-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20220607_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='resume.resume', verbose_name='Resume')),
            ],
        ),
    ]
