# Generated by Django 3.2 on 2022-06-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20220607_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('institute', models.CharField(blank=True, max_length=255, verbose_name='Institute')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseCertificate', to='resume.resume', verbose_name='Resume')),
            ],
        ),
    ]
