# Generated by Django 3.2 on 2022-06-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20220607_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Skill'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('level', models.IntegerField(choices=[(0, 'Excellent'), (1, 'Good'), (2, 'Medium'), (3, 'Weak')], verbose_name='Level')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='resume.resume', verbose_name='Resume')),
            ],
        ),
    ]
