# Generated by Django 3.2 on 2022-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20220607_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'Excellent'), (1, 'Good'), (2, 'Medium'), (3, 'Weak')], verbose_name='Level'),
        ),
    ]
