# Generated by Django 3.2 on 2022-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, 'Cycle'), (1, 'Diploma'), (2, 'Bachelor'), (3, 'Master'), (4, 'Doctorate'), (5, 'University'), (6, 'Student')], verbose_name='Grade'),
        ),
    ]
