# Generated by Django 3.2 on 2022-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_education_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='militaryـstatus',
            field=models.IntegerField(blank=True, choices=[(0, 'Subject'), (1, 'To Serving'), (2, 'EndـService'), (3, 'Exempt')], verbose_name='Military status'),
        ),
    ]
