# Generated by Django 3.2 on 2022-06-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_resume_militaryـstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecertificate',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='resume.resume', verbose_name='Resume'),
        ),
    ]
